project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
        verify: False
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false
    rinkeby:
        eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
        verify: True
    mainnet-fork-dev:
        eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
        verify: False
    ganache-local:
        verify: False

compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings:
        - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
        - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
    vyper:
        version: null

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

dev_deployment_artifacts: false
dotenv: .env

wallets:
    from_key: ${PRIVATE_KEY}